### ISSUE TITLE
Redirecionar para órgão ao vir da barra brasil

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#117]

**Comment by sahrosa** [comment]
Me preocupa essa issue de mandar o usuário diretamente para a página do órgão dentro do guia. Me preocupa pois criamos vários comportamentos diferentes: 
- quando acessa servicos.gov.br vai ir pra página inicial
- quando vier do Brasil.gov vai ir pra página inicial
- quando vier da Previdência, vai ir pra página da previdência
- ...

Consistência é uma das coisas mais importantes quando falamos em usuários muito principiantes que irão usar o site, e podem se perder com muita facilidade. Isso sem contar que ele(a) pode achar que continua no site do órgão, e assim não aprender que o site pode ser útil em vários outros momentos da vida dele(a).

**No entanto acho excelente a ideia de aproveitar o contexto de onde o cidadão veio!**
Quem sabe introduzimos uma área na página inicial com os serviços que tem mais a ver com o contexto de onde ele veio? 

Bom, essa é uma ideia! Podemos fazer uma sessãozinha de brainstorm pra ver como aproveitar isso! :)

**Comment by caduvieira** [comment]
:+1: para o contexto explicado pela @sahrosa

**Comment by cv** [comment]
Vou fechar esse cartão. Podemos reabri-lo no futuro, caso essa hipótese seja levantada novamente.
