### ISSUE TITLE
Barra Brasil deslocada em dispositivos móveis

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#121]
http://www.browserstack.com/screenshots/163e82b230d05e00879e5bd6a07e7ee0ad936259

Por exemplo, em um Samsung Galaxy S2 (note que a imagem tem 33px de margem ao topo):

![](https://www.browserstack.com/screenshots/163e82b230d05e00879e5bd6a07e7ee0ad936259/android_Samsung-Galaxy-S2_2.3_portrait.png)

**Comment by caduvieira** [comment]
Segunda dou uma olhada
