### ISSUE TITLE
Formulário mínimo para inserção de dados de serviço

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/guia-de-servicos#128]
Uma primeira versão como parte do processo de elaboração do novo Guia para Publicação de Serviços Públicos do Governo Federal, atualmente em elaboração pela ASEGE e DGE.

**Comment by oliviagj** [comment]
ver #44

**Comment by sahrosa** [comment]
Pessoal, porque enquanto o nosso modelo está assim!

Estamos vendo o que é realmente necessário, para priorizar em um modelo mínimo. A partir do modelo abaixo, estamos fazermos um "piloto" da Previdência, para validar detalhes (como quantidade de caracteres, campos fechados). 

- - -

```BUSCAR - O SERVIÇO```

# 1. Título
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

# 2. O que é?
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

### 2.1. Para que serve
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

### 2.2. Resultados (outcomes)
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

- - -

```ESCOLHER - COMO E QUANDO ACESSAR```

# 3. Para quem

### 3.1. Critérios de elegibilidade

Descrição do campo e orientações de preenchimento

    Colocar um exemplo

### 3.2. Segmentos da sociedade
Descrição do campo e orientações de preenchimento

	Colocar um exemplo

### 3.3. Eventos da vida
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

### 3.4. Áreas de interesse
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

- - -

# 4. Como fazer

### 4.1. O que é necessário
Descrição do campo e orientações de preenchimento

    Colocar um exemplo


### 4.2. É gratuito?
Descrição do campo e orientações de preenchimento

    Quanto custa?

### 4.3. Tempo total estimado
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

### 4.4. Próximo passo
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

# 5. Informações adicionais
Descrição do campo e orientações de preenchimento

	Colocar um exemplo

- - -


```INFORMAÇÕES EXTRA```

## Palavras-Chave
Descrição do campo e orientações de preenchimento

    Colocar um exemplo
    
## Órgão Responsável
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

## Órgão Prestador
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

## Status (Ativo/Inativo)
Descrição do campo e orientações de preenchimento

    Ativo / Inativo

## Legislação do Serviço
Descrição do campo e orientações de preenchimento

    Colocar um exemplo

**Comment by sahrosa** [comment]
Pessoal,
veja, abaixo como ficaria o modelo preenchido pelo serviço "Salário-maternidade":

```BUSCAR - O SERVIÇO```

# Título
Escreva o nome do serviço/benefício de forma curta e clara, para fácil compreensão do cidadão.

    Salário-maternidade

# O que é?
Descreva o que caracteriza e para que serve este serviço/benefício em até 500 caracteres.

    Este benefício tem como objetivo para dar suporte à trabalhadora durante um momento chave em sua vida, que é o nascimento de um filho. O salário-maternidade é pago em caso de nascimento de um filho (vivo ou morto), de aborto não criminoso, de adoção ou de guarda judicial para fins de adoção. 
        

#### O que você recebe:
Quais são os resultados que o cidadão poderá esperar deste serviço/benefício?

    Em regra, a duração deste benefício será de 120 dias, e a trabalhadora receberá o valor de R$00,00 em até x parcelas.

- - -

```ESCOLHER - COMO E QUANDO ACESSAR```

# Você tem direito?

#### Público-alvo:
Descreva brevemente quem são as pessoas que tem direito a este serviço/benefício.

    Quem tem direito a este benefício são mulheres brasileiras que tiveram um filho (vivo ou morto), de aborto não criminoso, de adoção ou de guarda judicial para fins de adoção.
    
	É importante ressaltar que o salário maternidade não poderá ser acumulado com:
	- Auxílio-doença ou outro benefício por incapacidade;
	- Seguro-desemprego;
	- Renda Mensal Vitalícia;
	- Benefícios de Prestação Continuada - BPC-LOAS;
	- Auxílio-reclusão pago aos dependentes.


- - -

# Como solicitar?

#### O que é necessário?
Descrição do campo e orientações de preenchimento    

	Para ter direito ao benefício a trabalhadora deverá atender, na data do parto, aborto ou adoção, aos seguintes requisitos:

	Se você estiver trabalhando: 
	* O pedido pode ser realizado a partir de 28 dias antes do parto.
    * Quantidade de contribuições (carência): 10 contribuições: para a trabalhadora Contribuinte Individual, Facultativa e Segurada Especial.
     
    Se você estiver desempregada, mas ainda na condição de seguradas do INSS:
    * O pedido somente será possível a partir da data do parto.
    * É necessário comprovar a qualidade de segurada do INSS e, conforme o caso, cumprir a quantidade mínima de contribuições necessárias.

    Em caso de adoção ou guarda judicial para fins de adoção: 
	* O pedido somente será possível após a decisão judicial.


#### Quanto custa?
Defina se o serviço custa para o cidadão e se sim, quanto?

    [x] Este servíco é gratuito para os cidadãos.
    [ ] Este serviço custa para os cidadãos.
    	- Quanto R$ [  ,  ]


#### Próximo passo para a solicitação:
Descreva quais são os possíveis próximos passos para a solicitação deste serviço/benefício.

    Faça seu pedido pela Internet: 
    Para sua maior comodidade, a Previdência Social disponibiliza o pedido online de salário-maternidade para mulheres empregadas (apenas nos casos de adoção ou guarda judicial para fins de adoção), empregada doméstica, contribuinte individual e facultativa. Esta forma de atendimento é fácil, rápido e simples, basta preencher o formulário com os seus dados e enviar os documentos solicitados à Previdência Social pelos Correios. Faça agora o seu pedido pela Internet. 
 
	Agende seu atendimento: 
	Para o atendimento presencial deste benefício, em uma das agências da Previdência Social, o agendamento é obrigatório. O agendamento poderá ser solicitado pela Central de Atendimento do INSS através do telefone 135, de segunda a sábado das 07:00 às 22:00 (horário de Brasília) ou diretamente pela internet através do link abaixo: Agende agora o seu atendimento.


#### Tempo estimado:
Descreva quanto tempo em média o cidadão levará para obter esse serviço/benefício.

    Acho que essa informação não pode ser básica pois é difícil de ser mensurada.

# Informações adicionais
Se ainda existir alguma informação que ainda não foi explicada para o cidadão, comente aqui neste campo.

	Para ser atendida nas agências do INSS, no mínimo deverá ser apresentado um documento de identificação com foto e o número do CPF.
	- A trabalhadora desempregada deve, obrigatoriamente, apresentar a certidão de nascimento (vivo ou morto) do dependente.
	- A trabalhadora que se afasta 28 dias antes do parto deve apresentar atestado médico original, específico para gestante.
	- Em caso de guarda, deve apresentar o Termo de Guarda com a indicação de que a guarda destina-se para adoção.
	- Em caso de adoção, deverá apresentar a nova certidão de nascimento expedida após a decisão judicial.


- - -


```INFORMAÇÕES EXTRA```

#### Palavras-Chave
Comente as palavras-chave que tem relação com este serviço/benefício.

    Maternidade; Salário; Trabalhadora; 
    
#### Órgão Responsável
Escolha o órgão responsável por este serviço/benefício.

    Ministerio da Previdencia Social - MPS

#### Órgão Prestador
Escolha o órgão que presta este serviço/benefício para o cidadão.

	Instituto Nacional do Seguro Social - INSS

#### Status (Ativo/Inativo)
Este serviço está ativo?

    - [x] Sim
    - [ ] Não

#### Legislação do Serviço
Qual é a legislação que assegura este serviço/benefício.

    ?????
    
#### Segmentos da Sociedade
Escolha um ou mais segmentos da sociedade que estão relacionados com este serviço.

	- Mulher; 

#### Eventos da Vida
Escolha um ou mais eventos da linha da vida que estão relacionados com este serviço.

    - Família e Filhos; 
    - Meus Direitos; 

#### Áreas de Interesse
Escolha uma ou mais áreas de interesse que estão relacionadas com este serviço.

    - Previdência Social; 
    - Trabalho; 
    - Saúde da mulher; 
    - Saúde da criança;

**Comment by cv** [comment]
Criei um formulário com todos os campos* lá no TypeForm pra gente testar.

Correndo, eu consegui cadastrar o serviço de Salário-Maternidade em 4 minutos (copiando e colando os valores), o que, para a quantidade de campos que temos, é bem satisfatório.

Eis a URL:

https://cv2.typeform.com/to/xAD6mP

Fiquem à vontade para cadastrar qualquer baboseira ali, a ideia é validar duas coisas:

- Que a experiência de cadastrar um serviço está OK
- Que os campos e descrições que estamos pedindo dos órgãos está OK

* Nem todos os campos tem 100% dos dados – ainda não importamos a lista de órgãos do SIORG.

**Comment by sahrosa** [comment]
Ótima ideia, @cv! :+1:  

Meus pontos:
- Levei 4 minutos, usando os dados já previamente organizados. Considero um bom tempo, mas podemos esperar que reestruturar a informação vai levar mais tempo. 
- Acho que vale fazermos com um novo serviço para ver quanto tempo leva - pode não ser um teste válido, pois não temos o conhecimento do serviço como os servidores que irão preenche-lo tem. Seria legal pedir pra alguém da previdência preencher um novo serviço e nos contar como foi/quanto tempo levou!
- Gostei da ideia do texto "Você tem direito a esse benefício?" ser mostrado como "Quem pode usufruir?". Podemos aplicar isso pra tudo, tendo portanto bem clara a visão do servidor que irá preencher, e a visão do cidadão que irá ler. Outro caso poderia ser o "O que esperar?" que ficaria "O que o cidadão pode esperar deste serviço?" e por aí em diante!
- Um caso que ficou confuso da primeira vez foi colocar '0' caso o serviço seja gratuito, mas uma vez aprendido, é tranquilo.
- Opções 8 e 9 ficaram confusas para preencher, e repetidas. Mas entendo que é por limitação da ferramenta.

**Comment by sahrosa** [comment]
Última versão do formulário ainda em discussão, conforme reunião da @oliviagj em BSB ontem. 

Enquanto ainda não está fechado, está neste docs: https://docs.google.com/a/thoughtworks.com/document/d/19HnevSGZucuvGP5lFyFBO6VONTbjimMIubEmPLZg05c/edit#

Abaixo está um primeiro wireframe:

![gds formulario minimo - wireframe](https://cloud.githubusercontent.com/assets/2932644/7025388/b9d63472-dd19-11e4-86c2-dd0d81ed758b.jpg)

**Comment by oliviagj** [comment]
Estamos trabalhando em cima do tema agora, pessoal, teremos novidades logo
mais.

Olivia Janequine | Gerente de projetosConsultora na *Thought*Works *Brasil*

*+55 51 92284372+55 51 98288123*


Em 7 de abril de 2015 11:32, Samantha Rosa <notifications@github.com>
escreveu:

**Comment by oliviagj** [comment]
Really @cv? Tá feito e aceito? Ou só caiu de maduro?

Escrito com os dedões por Olivia G. Janequine
Em 26/05/2015 11:32, "Carlos Villela" <notifications@github.com> escreveu:

**Comment by cv** [comment]
Foi pro outro repositório :)
