### ISSUE TITLE
Levantamento de sites do governo que apontam para o guia de serviços atual

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/guia-de-servicos#132]
Conforme o @cv no Gitter:
"alguns sites do governo tem um link direto pra busca do Guia!
http://portal.mec.gov.br/ por exemplo, tem um link “Serviços do MEC” que vai direto para uma página de busca do servicos.gov.br"

- É importante saber todos os portais do governo que apontam para o atual guia, principalmente quando mudanças começarem a ser feitas, pois isso pode quebrar esses outros portais;
- Além disso, é importante saber a forma como esses outros portais interagem com o Guia de Serviços, que funcionalidades utilizam como serviço, e em que contexto referenciam.

**Comment by jeankirchner** [comment]
@cv, @oliviagj Acho que o primeiro ponto é importante se estamos pensando em fazer um deploy para produção já no r0

**Comment by jeankirchner** [comment]
Uma forma "rápida" de conseguir uma lista de sites do governo, basta fazer uma pesquisa no google com "site:gov.br", que irá retornar todos os sites que o google tem indexado, dentro do domínio "gov.br".
<https://www.google.com.br/#q=site%3Agov.br>

**Comment by cv** [comment]
Acredito que levantar os sites que têm deep-links para o Guia não tem muito valor – podemos balizar a implementação de URLs de compatibilidade a partir dos acessos: só ver se algum 404 não deveria ser, e implementar o redirecionamento de acordo, como o @caduvieira fez no #130.

**Comment by almeidafab** [comment]
Por acaso descobri mais um portal que aponta serviços diretamente para o guia: http://www.brasil.gov.br/ (lado direito, abaixo de "Últimas Notícias")

**Comment by caduvieira** [comment]
Eles estão usando código 302 para apontar para os serviços de fato.
Poderiamos mapear mas acho que uma mudança deles seria mais adequada. Um
aviso para eles antes da mudança.

Em 30 de março de 2015 10:57, Fabrício Almeida <notifications@github.com>
escreveu:

**Comment by cv** [comment]
Caso isso seja complexo ou indesejável por algum motivo, parece que as URLs contém informação suficiente para fazer o redirecionamento do nosso lado, também. Quem pode ter essa conversa?

**Comment by cv** [comment]
@mformiga @almeidafab este cartão ainda está em aberto, e pode ser perigoso fazer o release 0 sem comunicar os administradores dos outros sites que o nosso esquema de URLs vai mudar, ou fazer com que as URLs legadas continuem funcionando de alguma maneira. Podemos retomar essa conversa?

**Comment by almeidafab** [comment]
@cv valeu pela lembrança. Vamos enviar um email aos gestores dos órgãos para que atualizem os links que apontam para o guia.

**Comment by cv** [comment]
Vou fechar esse cartão - agora que fomos para o ar, e #373, #369 e #130 foram implementadas, o jeito é monitorar 404s muito frequentes e adicionar novos redirecionamentos.
