### ISSUE TITLE
Busca exibida incorretamente (browser modo mobile)

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/guia-de-servicos#138]

**Comment by cv** [comment]
![screen shot 2015-03-24 at 9 16 29 am](https://cloud.githubusercontent.com/assets/5445/6801452/85203dea-d206-11e4-923b-94b6e3940e1f.png)

Este problema ainda acontece, @jeankirchner?

**Comment by jeankirchner** [comment]
Sim, voltou a acontecer essa situação na home page.

**Comment by jeankirchner** [comment]
Não acontece mais...
