### ISSUE TITLE
Teste automatizado para links quebrados (retornam status 404)

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/guia-de-servicos#139]
Algumas considerações:
- Podemos tentar utilizar o mapa do site (ou sitemap.xml que buscadores usam), e testar esses links (se forem públicos)
    - Ainda estamos organizando como o mapa do site (ou o xml dele) vai ficar, organizado pela #140
- Tomar cuidado para não ser um teste viciado, mas que de fato representaria a experiência do usuário (ex: fazer hardcode de links no teste pode fazer o teste passar e quebrar para o usuário, ou vice versa)

Alguma outra consideração?

**Comment by cv** [comment]
Este cartão é uma duplicata do #123.
