### ISSUE TITLE
"Porte de armas" aparece em "Adolescentes"

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/guia-de-servicos#141]

**Comment by mformiga** [comment]
Esta atividade de revisão de todas as linhas da vida está em andamento. No final, passaremos a lista atualizada. Dois comentários:

1. Não temos como alterar o xml gerado pelo guia pois esta opção de linha da vida já não existe para admin. Vamos enviar uma planilha atualizada com as associações que julgamos esterem corretas
2. Conforme falei em mensagem anterior "adolescentes" está relacionado a público-alvo específico e não a linha da vida. Para mim, pode retirar este item.

**Comment by mformiga** [comment]
"estarem"

**Comment by cv** [comment]
@mformiga não é mais fácil alterar o [arquivo de mapeamento diretamente](https://github.com/servicosgovbr/guia-de-servicos/blob/master/src/main/resources/application.yaml), ao invés de usar uma planilha e esperar algum desenvolvedor fazê-lo?

**Comment by cv** [comment]
Sobre o ponto 1, [achei um editor de linhas da vida](https://conteudo.servicos.gov.br/repositorioPublicoAlvo/cidadao/linhadavida.2011-10-06.9217097169) no admin atual, e a categoria "[Alistamento militar](https://conteudo.servicos.gov.br/repositorioPublicoAlvo/cidadao/linhadavida.2011-10-06.9217097169/eventodavida.2011-10-06.0809104914)" é o que associa porte de arma a adolescentes. Não tentei remover a associação por não estar familiarizado com o editor, por receio de apagar algo que não deveria. Pode conferir os links, @mformiga?

**Comment by mformiga** [comment]
@cv o arquivo de mapeamento não faz o mapeamento do serviço à linha da vida. O editor de linha da vida que vc apresentou realmente nos permite retirar/incluir/alterar a linha da vida exceto associá-la a algum serviço. Como não temos como fazer mais a associação correta via sistema , propomos enviar uma planilha atualizada para vocês. Tudo bem ? Alguma sugestão ?

**Comment by mformiga** [comment]
@cv coloquei a linha da vida adolescentes em esboço público. Deverá refletir no xml gerado pelo guia amanhã.

**Comment by mformiga** [comment]
@cv o que acha de enviarmos para vocês o xml já atualizado com as associações dos serviços às linhas da vida atualizadas ? Acho que facilita bem mais do que enviar uma planilha.

**Comment by cv** [comment]
Sim, facilita bastante! Se quiserem testar que o XML novo funciona, basta substituir o `src/main/resources/guiadeservicos.xml` pelo novo, iniciar o serviço e reimportar. Posso mostrar para vocês como fazer amanhã :)

**Comment by mformiga** [comment]
Legal. Até quinta-feira vamos ter o xml atualizado.

**Comment by oliviagj** [comment]
Duplicate da #142
