### ISSUE TITLE
Aprimorar seleção por público atendido

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/guia-de-servicos#145]

**Comment by jeankirchner** [comment]
"Serviços aos cidadãos", e "Serviços às Empresas" ao fim da página resolve?

**Comment by cv** [comment]
A ideia era ter mais públicos (empresas, cidadãos, ONGs, etc) ou usar uma categorização diferente para os públicos, similar às linhas da vida que temos hoje (aposentados, trabalhadores, etc)

**Comment by sahrosa** [comment]
Legal!! Começamos a falar sobre isso na #107

**Comment by jeankirchner** [comment]
Fechado, #107 vai cuidar desse assunto
