### ISSUE TITLE
Alguns elementos da página não respeitam alto contraste

### ISSUE THREAD

**Issue by erickpintor** [servicosgovbr/guia-de-servicos#161]
No que diz respeito a funcionalidade de alto contraste, os seguintes itens precisam de ajustes:
- [x] Barra com link de feedback no topo da pagina
- [x] Botão de "começar" ou "agendar" um serviço
- [x] Barra Brasil

***Dúvida***: É de nossa responsabilidade ajustar a Barra Brasil para funcionar com auto contraste?

**Comment by caduvieira** [comment]
Sobre a barra vou discutir aqui com a @garotadpi
Em 30/03/2015 16:10, "Erick Pintor" <notifications@github.com> escreveu:

**Comment by caduvieira** [comment]
A barra e rodapé vão ter suporte a contraste nela mesma. Basta adicionar/retirar a classe 'contraste' no body. Vou modificar a barra e o manual para isso.

**Comment by erickpintor** [comment]
Legal! Muito obrigado @caduvieira!

**Comment by caduvieira** [comment]
A barra já está pronta para alto contraste http://barra.governoeletronico.gov.br/teste . Agora é esperar entrar em produção.

**Comment by cv** [comment]
Woohoo! Valeu @caduvieira :+1:
