### ISSUE TITLE
Erro ao fazer uma busca contendo "/"

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/guia-de-servicos#170]

**Comment by erickpintor** [comment]
Segundo @almeidafab:

> acabei de fazer uma busca usando o termo "Pagamentos p/ DIRPF (carnê-leão, ganho de capital, etc)" e o resultado apresentou um erro...
Caso a falha persista, entre em contato com o suporte utilizando o identificador 99f3ec039f58.                                             não precisa ser agora, mas depois vocês verificam :)

**Comment by cv** [comment]
Alguns outros caracteres estão sendo interpretados pelo ElasticSearch – suspeito que no `queryString()`.
