### ISSUE TITLE
Destaques continuam exibidos em 3 colunas

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/guia-de-servicos#178]
Conteúdos da página inicial ficam uns sobre os outros, na listagem de serviços em destaque, quando usado em dispositivos móveis.

**Comment by cv** [comment]
Os destaques deveriam ser exibidos em apenas uma coluna, quando a tela não tem largura suficiente para exibir as 3.

**Comment by jeankirchner** [comment]
@erickpintor Até onde eu tinha visto, o problema é que a largura dos destaques não são fixas, são em relação à colunas. O layout tem 12 colunas, e a largura dos destaques são 3 de largura. E essa lógica se mantém no modo mobile.
