### ISSUE TITLE
vagrant-cachier não está funcionando

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#184]

**Comment by erickpintor** [comment]
Faltava a configuração do ```config.cache.scope``` que, neste caso, foi configurado para ser ```:box```.

Também criamos cache para o commando ```wget``` segundo a [documentação](http://fgrehm.viewdocs.io/vagrant-cachier/buckets/generic) do vagrant-cachier.

**Comment by cv** [comment]
👏👏👏



- cv
