### ISSUE TITLE
Tratamento de infos da semana 1 e 2

### ISSUE THREAD

**Issue by alklaser** [servicosgovbr/guia-de-servicos#19]
Agregar em planilha as informações que estão nos post-its das atividades rodadas na primeira semana para posterior tratamento.

**Comment by cv** [comment]
Ia ser uma boa publicar isso de alguma forma aqui no github. Dentro do `docs` já tem alguma coisa formatada, mas falta uma narrativa. Fica pra semana que vem, talvez?

**Comment by alklaser** [comment]
Comecei a colocar lá no docs mais coisas.
