### ISSUE TITLE
Títulos com palavras grandes quebram layout

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#195]
![screen shot 2015-04-24 at 1 04 22 am](https://cloud.githubusercontent.com/assets/5445/7312227/4d833e34-ea1e-11e4-9abc-cf5359a1940c.png)

**Comment by jeankirchner** [comment]
Os itens dessa grid, não deveriam ser posicionais. Eles deveriam ter um tamanho estático para serem apresentados, e ir quebrando conforme a tela vai diminuindo (a lá div com float left). 
Qual a melhor forma de lidar com a responsividade dessa grid?
