### ISSUE TITLE
'Buscar' exibido com pouca margem

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#197]
![screen shot 2015-04-24 at 1 10 31 am](https://cloud.githubusercontent.com/assets/5445/7312286/d1e228a2-ea1e-11e4-8c35-2ca86f56743c.png)

**Comment by erickpintor** [comment]
@cv Qual a resolução que você usou pra reproduzir este bug?

**Comment by cv** [comment]
@erickpintor estava usando o preset Galaxy Note II, em retrato.
