### ISSUE TITLE
VoiceOver não lê campo de busca

### ISSUE THREAD

**Issue by lmarquezini** [servicosgovbr/guia-de-servicos#202]
Texto que o VoiceOver lê no campo de busca (Chrome ou Firefox) deveria ler "Você pode pesquisar por assuntos, serviços, órgãos".

O VoiceOver diz que o campo é "campo texto em branco"

**Comment by erickpintor** [comment]
Este é um problema fácil de resolver. Eu só fiquei na duvida de fazer com que o leitor de tela diga o mesmo conteúdo que está no ```placeholder``` do campo é a melhor solução.

Tenho a impressão de que o ```placeholder``` funciona como um texto complementar ou um exemplo do tipo de informação que o campo pode aceitar, o que faz muito sentido pois podemos inferir o significado dado todo o contexto visual dos componentes da pagina. Porém, acredito que na condição de uma pessoa utilizando um leitor de tela, o texto será mais util se for mais descritivo ao invés de complementar.

Minha sugestão é que ao invés de "você pode pesquisar por assuntos, serviços, órgãos" o texto seja "Buscar por assuntos, serviços ou orgãos".

Isto já ocorre no site [brasil.gov.br](http://brasil.gov.br) onde o apesar do ```placeholder``` do campo de busca dizer "Buscar" os leitores de tela dizem "Buscar no portal".

O que acham, @cv e @sahrosa?

**Comment by sahrosa** [comment]
Apoio a ideia @erickpintor! Sem contar que quando fizermos um próximo teste usando o leitor de tela, poderemos validar se os usuários também concordam.

Só pra complementar: no teste que fizemos com o usuário usando o leitor de tela, no chrome não leu nada, como o @lmarquezini comentou na issue. Mas no IE leu a mensagem "Você pode pesquisar...." e o usuário entendeu o que era pra fazer. Mas acho que a como tu sugeriu ficará mais objetivo :)
