### ISSUE TITLE
Navegação por tab no Safari quebrada

### ISSUE THREAD

**Issue by lmarquezini** [servicosgovbr/guia-de-servicos#203]
Ao navegar usando tabs, deveria pular entre os links. Atualmente, o navegador alterna entre a barra de URL e o campo de texto da busca.

**Comment by cv** [comment]
O Full Keyboard Access está ligado?

**Comment by lmarquezini** [comment]
Estava ligado em "Text boxes and lists only" e a navegação no browser safari era somente entre o campo de url do browser e o campo de busca do site. Nos outros browsers estava navegando entre todos os links do site (como esperado).

Ao configurar para "All controls" (na opção de Full Keyboard Access), no browser safari continua acessando os dois campos como na opção anterior mas agora também é possível acessar as opções dos favoritos do browser. O usuário continua sem acessar os links das páginas.

**Comment by cv** [comment]
Este é o comportamento esperado do Safari. Para navegar entre todos os elementos, use Option-Tab (ou mude as opções de acessibilidade nas preferências).

**Comment by sahrosa** [comment]
Precisamos alterar a página de Acessibilidade para descrever que a navegação no Safari deverá funcionar com Option+Control.

**Comment by cv** [comment]
@sahrosa a navegação entre links não está descrita na página de acessibilidade, até onde eu vi. Mas, se quiser adicionar essa informação, não vejo nada contra. :)
