### ISSUE TITLE
Alto Contraste não permanece habilitado entre as sessões/navegação

### ISSUE THREAD

**Issue by lmarquezini** [servicosgovbr/guia-de-servicos#204]
Ao navegar entre os diferentes níveis das páginas do site, uma vez ativando o alto contrate, as páginas seguintes deveriam permanecer com o alto contrate habilitado.

Passos:
1. Habilitar o ALTO CONTRATE na página inicial;
2. Acessar qualquer link;
3. Verificar se o alto contraste permanece habilitado.

Resultado esperado:
Uma vez ativado o alto contraste, todas as páginas durante a navegação deveriam estar com o alto contraste ligado.

Resultado atual:
É necessário ativar o alto contraste para cada nível de navegação.

**Comment by cv** [comment]
Parece que ainda está ocorrendo, pelo menos no Chrome local aqui.

**Comment by erickpintor** [comment]
Não consegui reproduzir. Testei no Chrome, Firefox e Safari.
@cv Pode tentar novamente fazendo um favor?

**Comment by cv** [comment]
A boa notícia é que eu não consegui reproduzir depois de limpar os cookies
e tentar de novo. Podemos mover!

(A má notícia é que eu não sei como isso quebrou, funcionou, quebrou de
novo e agora voltou a funcionar…)

**Comment by erickpintor** [comment]
Ok. Vamos continuar atentos a isso.

Fiz uma alteração pra verificar os cookies também na renderização da pagina principal ao invés de deixar para verificar só no JS.

Antes, a pagina "piscava" durante a navegação, o que é uma experiência muito ruim quando o auto contraste está habilitado.

O que acha? -> https://github.com/servicosgovbr/guia-de-servicos/commit/36fdb1bcc11fbc5a9cc1eff8828b23265b4246cd

**Comment by cv** [comment]
Excelente! :) Valeu, @erickpintor!
