### ISSUE TITLE
Agrupar configurações de monitoramento

### ISSUE THREAD

**Issue by erickpintor** [servicosgovbr/guia-de-servicos#210]
Para ativar o monitoramento do guia de serviços usando o Piwik é necessário ativar o profile ```monitoring``` nas configurações do site. Porém, as configurações como ```url```, ```id``` do site e ```token``` do Piwik se encontram em suas configurações gerais (```application.yaml```).

Acredito que este formato possa confundir os contribuidores do projeto.

Podemos mover todas as configurações de monitoramento para um arquivo ```application-monitoring.yaml``` a fim de deixar mais claro a existência deste profile.

**Comment by cv** [comment]
:-1: - o arquivo só teria 4 linhas, o que eu não acho que faz tanta diferença assim no entendimento. Todo caso, a documentação sobre as variáveis do Piwik poderia ser mais completa…

**Comment by erickpintor** [comment]
Meu ponto não é com relação a complexidade da configuração, mas sim pelo fado de não existir "cola" alguma entre o perfil ```monitoring``` e suas configurações.

Um contribuidor desavisado poderia muito bem apagar o perfil ```monitoring``` do código acreditando que ele não seve pra nada dado a ausência de um arquivo de configuração com o mesmo prefixo (considerando as convenções do Spring).
