### ISSUE TITLE
Visualização de serviços por ordem alfabética

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/guia-de-servicos#224]
Não estamos mostrando os serviços em ordem alfabética nos seguintes casos: 

Exemplo: **Autorização para Acesso Provisório a Recinto Alfandegado** está vindo antes de **Acesso ao Sistema SISCOSERV**.

- [x] Órgãos de A a Z
- [ ] Serviços de A a Z
- [ ] Serviços aos cidadãos
- [ ] Serviços às empresas

**Comment by cv** [comment]
Excelente bug :)




Já achei a solução, push depois do almoço!



- cv
