### ISSUE TITLE
Atalho de busca na home não deixa campo ativo

### ISSUE THREAD

**Issue by lmarquezini** [servicosgovbr/guia-de-servicos#234]
USABILIDADE: Ao utilizar essa opção, o campo de busca não fica ativo forçando assim que o usuário:
1. Com o mouse clique novamente no campo de busca (logo o link é apenas para a posição não para a funcionalidade) para ele ficar ativo;
2. Navegando com TAB, vá para o próximo campo e volte para o campo de texto do busca.

Ver essa funcionalidade no site: http://www.brasil.gov.br/

**Comment by jeankirchner** [comment]
@erickpintor este card está sendo feito?

**Comment by erickpintor** [comment]
@jeankirchner Está sim.
