### ISSUE TITLE
Fontes estão renderizando em um peso menor nos celulares

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/guia-de-servicos#242]
Vejam abaixo a imagem da home renderizada em um Moto G:

![screen shot 2015-05-05 at 6 40 13 pm](https://cloud.githubusercontent.com/assets/2932644/7483592/6740c54e-f356-11e4-8d08-ae21a4cb7ac7.png)

E aqui ela renderizada no simulador do mac:

![image](https://cloud.githubusercontent.com/assets/2932644/7483529/0f6ef53e-f356-11e4-994d-e8cdc41b01ab.png)

**Comment by jeankirchner** [comment]
Tentamos alguns ajustes simples, mas não funcionaram. Existe outro possível ajuste, descrito aqui:
http://stackoverflow.com/questions/11289166/chrome-on-android-resizes-font

Mas existem riscos de grandes quebras de layout em algumas plataformas/dispositivos, que seriam muito mais graves que o problema indicado por esse ticket.

Futuramente vamos revisitar esse bug, e tentar encontrar alguma ajuste menos impactante.
