### ISSUE TITLE
Verificar erros e warnings indicados pelo Chrome Audit

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/guia-de-servicos#243]
Ele roda só na página aberta, então temos que rodar em algumas páginas que temos (que não são muitas).

Não é tudo o que o Audit indicar que deve ser removido, por exemplo, ícones do font awesome (ainda) não utilizados vão aparecer como regras de css não são utilizados.

![screen shot 2015-05-06 at 11 19 50](https://cloud.githubusercontent.com/assets/576918/7495155/85d67760-f3e2-11e4-9538-8f22409645f4.png)

**Comment by cv** [comment]
Nenhum erro apontado causa grandes problemas, ou tem uma correção mais custosa do que deixar as coisas como estão.

Precisamos reavaliar antes do Release 2.
