### ISSUE TITLE
A página de feedback está com o cabeçalho cortado

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/guia-de-servicos#253]
Como não mostramos a barra de feedback, o cabeçalho está cortado em desktop, tablet e mobile:

![image](https://cloud.githubusercontent.com/assets/2932644/7522910/a57111ec-f4ce-11e4-80b1-ae27bd8da5f2.png)

![image](https://cloud.githubusercontent.com/assets/2932644/7522916/af04c3b6-f4ce-11e4-81d8-f274c94fbdd6.png)

E deveria estar igual com tamanho igual a quando existe barra de feedback:

![image](https://cloud.githubusercontent.com/assets/2932644/7522944/ce72301c-f4ce-11e4-8730-48425dcab242.png)

**Comment by sahrosa** [comment]
O cabeçalho deveria ser do tamanho que ele é nas outras páginas, mas está maior, porque onde a barra de feedback aparecia, agora está uma faixa cinza, @jeankirchner.

Ou seja, nesta página o cabeçalho está 33px maior do que deveria se.r!

**Comment by jeankirchner** [comment]
@sahrosa: Isso pode ser um erro diretamente relacionado à implementação desse cartão, ou até o impacto de alguma outra alteração. Sugiro abrir uma issue para isso :)
