### ISSUE TITLE
Visão do Dashboard de Métricas

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/guia-de-servicos#254]
Na [documentação](http://servicosgovbr.github.io/guia-de-servicos/metricas/index.html) é possível encontrar todos os tipos de informação que poderiam ser consideradas no dashboard de métricas.

**Comment by sahrosa** [comment]
Pessoal,
vejam uma primeira versão de como poderá ser o nosso dashboard de métricas:

![gds -pagina-de-metricas](https://cloud.githubusercontent.com/assets/2932644/7574767/2eb36434-f806-11e4-8477-b46aa0ca541b.jpg)

**Comment by claudiamelo** [comment]
Para aumentar a legibilidade dos gráficos, adicionar os eixos (x/y).
Complitude -> Completude. 
Painel de métricas --> Plataforma de desempenho.

**Comment by sahrosa** [comment]
Visão da página inicial apenas com dados gerais, o que acham? @claudiamelo :)

![gds -pagina-de-metricas-1](https://cloud.githubusercontent.com/assets/2932644/7595310/a838db0c-f8bc-11e4-9a7b-977bbecd58a7.jpg)

**Comment by sahrosa** [comment]
E aqui a última versão. A partir disso podemos começar a pensar melhor nas nossas KPIs e também outras métricas que podem ser interessantes.

![gds -pagina-de-metricas-1](https://cloud.githubusercontent.com/assets/2932644/7616950/83e68476-f97e-11e4-90db-b7b79d5d48a3.jpg)
