### ISSUE TITLE
Corrigir busca

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/guia-de-servicos#258]
- Fiz a busca inserindo aleatoriamente caracteres “sfgrv”. Foram retornados 3 resultados
-  Fiz a busca inserindo “1” no campo de busca. Foram retornados 18 resultados. Qual o critério para esse resultado ? Por quê aparece a paginação para um resultado de 18 serviços e não aparece paginação ao escolher uma linha da vida com dezenas de serviços ?
- Após pesquisar “Secretaria de aviação civil” aparecem vários serviços não relacionados. Este órgão possui apenas um serviço

**Comment by cv** [comment]
A busca por "sfgrv" retornou os 3 resultados por conter a palavras "serve" ou "servem", que o ES entende como grafias alternativas.

Já a busca por "1" retornou, por exemplo, [notificacoes-sms-do-simples-nacional](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico/notificacoes-sms-do-simples-nacional) por conter esse número da URL do serviço (`http://www8.receita.fazenda.gov.br/SIMPLESNACIONAL/Servicos/Grupo.aspx?grp=t&area=1`)

"Secretaria de aviação civil" retorna diversos resultados relacionados às palavras "secretaria", "aviação" e "civil" - note que existem diversos resultados relacionados à construção civil, por exemplo. [Pesquisando as palavras entre aspas duplas, a ambiguidade desaparece.](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/busca?q=%22Secretaria+de+avia%C3%A7%C3%A3o+civil%22)

**Comment by cv** [comment]
@mformiga, concorda em fechar esse cartão e abrir outros específicos caso ainda persistam? Não vejo este como um bug.

**Comment by mformiga** [comment]
Tudo bem, @cv . No entanto, poderia informar por que o elastic retorna para esse string que não faz sentido ? Não vi relação nenhuma, por isso achei que poderia ser um bug desconhecido que poderia influenciar em outras buscas.

**Comment by sahrosa** [comment]
Não temos como "calibrar" pra termos uma grafia alternativa mais seletiva? Porque realmente "sfgrv" está muito longe de  "serve". Não tem nenhuma vogal... acho que precisamos considerar casos como "CNH" e "CHN" ou "restituição" e "retistuição" ou "retituição" por exemplo mas extremos como "sfrgv" podem estar aumentando a quantidade de resultados potencialmente, não?

**Comment by cv** [comment]
Hoje o 'fuzziness' está configurado em 2:

https://github.com/servicosgovbr/guia-de-servicos/blob/master/src/main/java/br/gov/servicos/busca/BuscadorConteudo.java#L52-52

Podemos diminuir, mas aí menos buscas com erros de grafia vão trazer resultados (`chn` -> `cnh` e `retituição` -> `restituição` continuariam funcionando por só ter 1 troca, mas `pasaprote` não acharia `passaporte`, por exemplo)

**Comment by sahrosa** [comment]
Hmmm. Bom ponto @cv. O que acha @mformiga?

**Comment by mformiga** [comment]
Acho que o prejuízo de não retornar para duas trocas é maior do que retornar estranhamente em mais trocas que aparentemente não fazem sentido. Podem manter, então. Valeu.
