### ISSUE TITLE
Corrigir texto de busca vazia.

### ISSUE THREAD

**Issue by mformiga** [servicosgovbr/guia-de-servicos#259]
Após fazer busca vazia, o texto explicativo fala em palavra-chave. Acredito que este termo não seja de conhecimento amplo para os cidadãos. Além disso, está utilizando os termos “palavra-chave” “termo” com o mesmo significado.

**Comment by sahrosa** [comment]
Estava dando uma olhada aqui agora e percebi que esse botão não deveria funcionar, caso o usuário não tenha preenchido nenhum texto. 

Esse bloqueio acontece em vários sites importantes: New York Times, Terra, Globo.com, etc. 

Criei a issue #283 para resolver isso.
