### ISSUE TITLE
Link para feedback sendo identificado como link para podcasts

### ISSUE THREAD

**Issue by erickpintor** [servicosgovbr/guia-de-servicos#279]
Quando o celular possui alguma APP para gerenciar podcasts (Podcast Addict, por exemplo) o link para página de feedback oferece a opção de abrir a página com a APP de podcasts.

**Comment by erickpintor** [comment]
![screenshot_2015-05-13-13-36-30](https://cloud.githubusercontent.com/assets/813042/7615696/a72f7c8e-f975-11e4-8ba0-4373113d67ca.png)

**Comment by erickpintor** [comment]
Eu suspeito que o problema seja a string ```feed``` dentro do link: ```/feedback?url=/&ticket=83dee3b98527&busca=```

**Comment by cv** [comment]
Ainda acontece, @erickpintor? Estou sem um dispositivo Android para testar...

**Comment by erickpintor** [comment]
@cv Parou de acontecer. Ta tudo certo agora.

**Comment by cv** [comment]
:dancer:
