### ISSUE TITLE
/health respondendo DOWN

### ISSUE THREAD

**Issue by caduvieira** [servicosgovbr/guia-de-servicos#289]
Health está respondendo DOWN mas o serviço de busca está funcionando corretamente.

![image](https://cloud.githubusercontent.com/assets/3831408/7654439/7794d076-faf3-11e4-8558-bba63bf5f117.png)

**Comment by cv** [comment]
Isso é de propósito, @caduvieira - o status `YELLOW` serve para chamar a atenção de que só existe um nodo no cluster do ElasticSearch no ambiente da EC2. Como a API de monitoramento de saúde do Spring só tem UP e DOWN, preferi deixar qualquer aviso como DOWN, para que não passe despercebido por muito tempo.

**Comment by caduvieira** [comment]
Blz
