### ISSUE TITLE
Resultados de busca não estão aparecendo

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/guia-de-servicos#295]
Para qualquer palavra buscada não é apresentada a lista de resultados, apenas a paginação e o contador

**Comment by cv** [comment]
A versão 1.2.4.SNAPSHOT do Spring-Boot introduziu este bug. Resolvemos indo para a versão 1.2.3.RELEASE, que não possui o problema.

É provável que o pessoal do Spring resolva este problema em breve (talvez na 1.2.5.SNAPSHOT ou até na 1.2.4.RELEASE, mesmo). Quando isso acontecer, voltaremos a a seguir as versões mais recentes.
