### ISSUE TITLE
Menu "Categorias" está com margens

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/guia-de-servicos#297]
Entre os breakpoints 693px e 460px está acontecendo alguns bugs:
- [x] Aparecendo uma margem no menu Categorias.
- [ ] Sem separação entre menu e cabeçalho na página de feedback.

![image](https://cloud.githubusercontent.com/assets/2932644/7689277/6584769e-fd81-11e4-8f05-58fcc49a8899.png)

Em 576px está mostrando assim junto com a migalha-de-pão:

![screen shot 2015-05-18 at 5 23 07 pm](https://cloud.githubusercontent.com/assets/2932644/7689435/a1773398-fd82-11e4-80cd-4b9c8236d47d.png)

**Comment by jeankirchner** [comment]
@sahrosa que tipo de separação precisamos entre o menu e o header na página de feedback?
Algo como uma margem de 10px no topo?

**Comment by sahrosa** [comment]
Acho que 1px solid #d5d5d5 resolve @jeankirchner, mais ou menos assim:

![screen shot 2015-05-20 at 1 44 12 pm](https://cloud.githubusercontent.com/assets/2932644/7731373/521e72dc-fef6-11e4-8f3b-4ee29758c107.png)

**Comment by jeankirchner** [comment]
:+1:
