### ISSUE TITLE
Links com font-size diferentes

### ISSUE THREAD

**Issue by trecenti** [servicosgovbr/guia-de-servicos#302]
Pode ser observado nessa [página](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico/multas-de-transito-departamento-de-policia-rodoviaria-federal)

Exemplo:
![screen shot 2015-05-19 at 9 59 48 am](https://cloud.githubusercontent.com/assets/314872/7703374/e7e674f2-fe0d-11e4-9306-61b994848287.png)

Font sizes (computed)
![screen shot 2015-05-19 at 10 00 20 am](https://cloud.githubusercontent.com/assets/314872/7703373/e7d01b1c-fe0d-11e4-9d85-97cd11b911d0.png)
![screen shot 2015-05-19 at 10 00 09 am](https://cloud.githubusercontent.com/assets/314872/7703375/e7e9a4ec-fe0d-11e4-87df-6ff072d0e856.png)

**Comment by jeankirchner** [comment]
Os diferentes "font-size" computados agora estão padronizados.

Existe um problema um pouco mais genérico que identificamos, que apesar de colocar um font-size explicitamente (mesmo com !important), o valor computado não necessariamente será o mesmo. 

Mais estranho ainda, a cada nível de "<span>" que um conteúdo está, o font-size computado fica um pouco menor, e não conseguimos rastrear a origem de algum estilo que faz isso.
