### ISSUE TITLE
Deployment do Alpha

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#31]
Heroku + importação

**Comment by cv** [comment]
Woohoo! :clap: 

http://gds-alpha.herokuapp.com/

**Comment by nitaibezerra** [comment]
Yeah!

Mas aqui deu erro pra mim..
Em 06/02/2015 22:22, "Carlos Villela" <notifications@github.com> escreveu:

**Comment by cv** [comment]
O índice do ElasticSearch tem que ser refeito a cada deployment (não é o ideal para homologação ou produção, mas ajuda a evitar _leaks_ enquanto estivermos testando).

Adicionei um passo ao build no [Snap](https://snap-ci.com/servicosgovbr/guia-de-servicos/branch/master/) para re-importar o XML ao final de cada deploy. Vamos ver se resolve…

**Comment by nitaibezerra** [comment]
Agora tá ok.

**Comment by cv** [comment]
:boom:
