### ISSUE TITLE
Renomear linhas da vida

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/guia-de-servicos#314]
Pessoal,
Em reunião com a ASEGE e SEGEP chegamos a um entendimento de que será melhor renomear as linhas da vida da seguinte forma:

- [x] DE: Administrar um Negócio PARA: Empreendedorismo e negócios
- [x] DE: Aposentar-se PARA: Aposentadoria
- [x] DE: Cuidar da Saúde PARA: Cuidados com a saúde
- [x] DE: Emitir seus Documentos PARA: Documentos e certidões
- [x] DE: Estudar PARA: Estudos
- [x] DE: Exportar Produtos e Serviços PARA: Exportação de produtos e serviços
- [x] DE: Importar Produtos e Serviços PARA: Importação de produtos e serviços
- [x] DE: Manter um Veículo PARA: Veículos
- [x] DE: Obter Crédito e Apoio Financeiro PARA: Apoio financeiro e crédito
- [x] DE: Pagar Contas e Impostos PARA: Contas e impostos
- [x] DE: Ter um Imóvel PARA: Imóveis
- [x] DE: Ter uma Família PARA: Família
- [x] DE: Trabalhar PARA: Profissão e trabalho
- [x] DE: Viajar para o Exterior PARA: Viagem ao exterior
- [x] DE: Vir para o Brasil PARA: Estrangeiros no Brasil

**Comment by cv** [comment]
Fiz uma confusão na hora de gerar os commits, e todos eles foram atribuídos ao cartão #315. :(
