### ISSUE TITLE
DAP é do MDA ou MAPA?

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#329]
Revisando conteúdo dos órgãos, notei que a emissão da Declaração de Aptidão da Agricultura Familiar - DAP está descrita como destaque de ambos:

![screen shot 2015-05-21 at 8 58 03 pm](https://cloud.githubusercontent.com/assets/5445/7761434/1d1c8b30-fffc-11e4-9d08-22386f984cb2.png)

![screen shot 2015-05-21 at 8 58 35 pm](https://cloud.githubusercontent.com/assets/5445/7761443/2f39b69e-fffc-11e4-9943-cb502884eb9e.png)

O serviço em si [sugere que esta emissão é feita pelo MDA](http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/servico/emissao-da-declaracao-de-aptidao-da-agricultura-familiar-dap).

**Comment by erickpintor** [comment]
Devemos retirar o serviço do órgão que não presta o serviço.
