### ISSUE TITLE
Legend dos formulários de busca

### ISSUE THREAD

**Issue by caduvieira** [servicosgovbr/guia-de-servicos#341]
A classe .hidden está colocando display: none[1] e o mesmo é ignorado pelos leitores de tela.
Se a intenção é que seja lido pelos leitores de tela tem que usar outra abordagem [2]

[1] http://ec2-54-94-244-36.sa-east-1.compute.amazonaws.com/busca?q=inss
[2] http://webaim.org/techniques/css/invisiblecontent/

**Comment by caduvieira** [comment]
Podia também dar um destaque maior para a busca
![image](https://cloud.githubusercontent.com/assets/3831408/7775869/2b761e08-008d-11e5-989e-22b05abb1113.png)

**Comment by sahrosa** [comment]
Legal @caduvieira! Vou propor algo em cima da tua proposta!
