### ISSUE TITLE
Sugestão: Icone do github na página de serviços quase invisível

### ISSUE THREAD

**Issue by juniorvanin** [servicosgovbr/guia-de-servicos#346]
O Icone do github na página de serviços que redireciona o usuário para que que as informações sejam editadas é muito pequeno e quase imperceptível, eu quase não consegui enxergar, acredito que uma pessoa com problemas de visão não poderá enxergá-lo.  Dica: adicione um label "clique aqui para editar" ou algo do tipo, junto com o icone.

**Comment by sahrosa** [comment]
Oi @juniorvanin, comentamos isso ontem @cv e eu. Mas não está claro o quanto queremos dar de visibilidade para isso. Por isso, vamos pensar em como mostrar isso melhor, mas obrigada pela issue!

**Comment by carolmartinussi** [comment]
O link do git estar "invisível" neste momento parece fazer sentido como parte da estratégia (só mostrar que funciona). Talvez, para logo mais, poderíamos utilizar algo mais "user friendly" (ex: link "ajude a melhorar esta página"). Então seria preciso pensar se será necessário criar mais uma etapa no fluxo de edição, como por ex preenchimento de formulário, uma vez que nem todo usuário tem familiaridade com o git.

**Comment by cv** [comment]
Posso fechar este cartão por enquanto, e abrimos outro quando tivermos o editor funcionando?

**Comment by sahrosa** [comment]
Sim!
