### ISSUE TITLE
Nº de resultados encontrados em uma busca não é exibido acima da listagem

### ISSUE THREAD

**Issue by carolmartinussi** [servicosgovbr/guia-de-servicos#356]
Nº de resultados de busca é exibido apenas abaixo da listagem

![image](https://cloud.githubusercontent.com/assets/12464088/7778497/8b9e67b2-00a2-11e5-8715-aa00cf583bd7.png)

**Comment by cv** [comment]
Relacionado: #269

**Comment by cv** [comment]
Decidimos que o comportamento da #269 é preferível no momento. Fechando esse cartão.
