### ISSUE TITLE
Campo de busca sem limite de caracteres resulta em erros na página

### ISSUE THREAD

**Issue by Rliedke** [servicosgovbr/guia-de-servicos#366]
Inserindo inúmeros caracteres e clicando em buscar resulta em erros na página. Verificar se não esta tendo Exceptions no log.

![limite_caracteres](https://cloud.githubusercontent.com/assets/5034279/7781829/46ab715e-00cf-11e5-9b32-9fd0bc438294.jpg)

**Comment by cv** [comment]
Ainda é possível fazer requisições HTTP com strings maiores: é possível passar por cima do `maxlength`, mas como os erros só ocorrem além de 1024 caracteres, e não prejudicam o sistema, acho que podemos fechar esse bug. De acordo, @rliedke?

**Comment by Rliedke** [comment]
De acordo @cv. Obrigada
