### ISSUE TITLE
Voltar para o topo deixa a barra brasil escondida

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/guia-de-servicos#367]
Ao usar o link "voltar para o topo, o site volta até o cabeçalho, deixando a barra brasil escondida.

**Comment by cv** [comment]
Este comportamento está consistente com o Portal Brasil e outros sites do governo.

**Comment by sahrosa** [comment]
Verdade @cv! Conferi agora... @mformiga @almeidafab está correto assim mesmo?

**Comment by mformiga** [comment]
@caduvieira é isso mesmo ?

**Comment by jeankirchner** [comment]
@caduvieira - podemos fechar esse cartão?

**Comment by almeidafab** [comment]
conversei com o @caduvieira e ele disse que está correto esse comportamento. @sahrosa @ jeankirchner
