### ISSUE TITLE
Menu está quebrando nas páginas de serviços

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/guia-de-servicos#378]
Conforme imagem abaixo, está ficando com um espaço entre menu e cabeçalho, além de colar o menu na migalha-de-pão. Aparentemente esse comportamento só aparece em serviços com mais de duas linhas de título.
![image](https://cloud.githubusercontent.com/assets/2932644/7838685/9f50bcd6-0464-11e5-9bb9-3d193c028c7c.png)

**Comment by jeankirchner** [comment]
Esse bug é mais chato do que parece, então eu fiz da forma mais simples, estabelecendo uma altura para as migalhas que suporte uma possível quebra de linha, e posicionando os elementos relativamente de acordo com essa altura.

*Se alguém quiser saber a explicação, e as soluções que não deram certo, continue lendo.*

**O problema**
O menu de categorias, na ordem de elementos do html, está abaixo das migalhas. Para posicionar o menu acima das migalhas, é necessário fazer um posicionamento relativo, baseado na altura das migalhas. Então se as migalhas ocupa uma altura "X" (desconsiderando margens e etc),  é necessário posicionar o menu na posição "-X". 
Quando as migalhas tem um texto muito grande e quebra a linha, a altura das migalhas muda. Os posicionamentos relativos teriam que mudar também, portanto um valor estático no CSS não resolve.

**As tentativas**
- Usando flexbox, é possível dizer a ordem dos elementos no DOM, e eu faria utilizando media queries para alternar entre mobile/tablet/desktop, e ficaria tudo certo, se o resto da página inteira não tivesse quebrado;
- Usando um truque de "display: none" e "display: initial" para ter um menu antes e um depois, que seriam alternados com media queries. Mas teria problema de ter dois itens com mesmo id, além de que o código não estava ficando bom.

**Comment by sahrosa** [comment]
:+1:
