### ISSUE TITLE
Descrição da SPI vs SPU

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#382]
A descrição da missão da SPI parece ser da SPU:

http://servicos.gov.br/orgao/secretaria-de-planejamento-e-investimentos-estrategicos-spi
http://servicos.gov.br/orgao/secretaria-do-patrimonio-da-uniao-spu-mp

**Comment by cv** [comment]
@almeidafab @mformiga podem dar uma olhada com o pessoal da ASEGE e retornar pra gente?

**Comment by almeidafab** [comment]
@cv o texto correto da SPI é este:
"Unidade do Ministério do Planejamento, Orçamento e Gestão, responsável pela elaboração do Plano Plurianual (PPA), também atuando na análise dos investimentos e gastos estratégicos de governo, com atenção ao impacto territorial e a articulação dos investimentos privados e de estados e municípios, para promover uma cooperação federativa em prol do desenvolvimento. 
Dentre os serviços ofertados ao público está o acesso à Biblioteca Digital do Desenvolvimento (BibSPI)."
