### ISSUE TITLE
Texto comum (<p> e <a>) está com 16px ao invés de 15px

### ISSUE THREAD

**Issue by sahrosa** [servicosgovbr/guia-de-servicos#389]
Estamos mostrando o texto maior que o padrão da SECOM. Precisamos voltar a mostra-lo com 15px.

**Comment by jeankirchner** [comment]
Relacionado com a #320.

**Comment by cv** [comment]
Vou tornar os `font-size`s da aplicação inteira relativos a `em(15)`, assim fica mais fácil resolver qualquer problema de escala. Commit em alguns minutos…

**Comment by jeankirchner** [comment]
Uma coisa que eu já vi em relação ao Bourbon Neat, eles usam essa variável como base para os cálculos de tamanho:

```
$em-base: 16px;
```
