### ISSUE TITLE
Cobertura de código reportada incorretamente (lombok)

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#39]
Após a configuração do [Coveralls](https://coveralls.io/r/servicosgovbr/guia-de-servicos), percebemos que o relatório inclui muitos métodos como `equals()` e `hashCode()`, gerados automaticamente pelo Lombok, estão sendo contados como falhas na cobertura de testes.

**Comment by rodrigomaia17** [comment]
Alguma idéia de solução?

**Comment by rodrigomaia17** [comment]
@cv Alguma idéia de solução?

**Comment by cv** [comment]
Nada de bom até agora. Os dois projetos estão apontando um ao outro como a fonte do problema, e nada saiu do lugar :(

https://code.google.com/p/projectlombok/issues/detail?id=589

Tem uma [classe do Guava](https://code.google.com/p/guava-libraries/source/browse/guava-testlib/src/com/google/common/testing/ClassSanityTester.java) que pode ajudar a testar todos os métodos gerados, no entanto.

**Comment by rodrigomaia17** [comment]
Isto foi contornado?

**Comment by erickpintor** [comment]
Ainda não @rodrigomaia17. Mesmo com esse problema, nosso coverage está em 90%.
Esta issue não tem sido prioridade no momento.

**Comment by rodrigomaia17** [comment]
@cv Resolveram ou o impacto disso não interessa mais?

**Comment by cv** [comment]
Vamos trocar para o [sonarqube](www.sonarqube.org), que não apresenta esse problema :)
