### ISSUE TITLE
Substituir o título "Canais de comunicação..." por "Canais de prestação...""

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/guia-de-servicos#396]
Fazer a alteração no formulário no título "Canais de comunicação..." para "Canais de prestação..."
O termo canais de comunicação pode confundir o usuário a pensar em canais de contato, tipo ouvidoria etc

**Comment by cv** [comment]
Movendo para https://github.com/servicosgovbr/editor-guia-de-servicos/issues/68
