### ISSUE TITLE
Analisar Eventos das Linhas da Vida

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#58]
Relacionados - #55 e #57

**Comment by oliviagj** [comment]
Essas issues de análise geram o que exatamente? ou elas são só um passo necessário para alguma outra coisa que gera valor?

**Comment by cv** [comment]
Criei essas issues para a gente poder avaliar os dados existentes, e se eles poderiam ser úteis na navegação dos usuários antes de termos ferramental para editar e re-categorizar os serviços. Como ficou combinado que vamos usar linhas da vida como navegação principal por enquanto (discussão na #84), podemos deixar os eventos para outra hora.
