### ISSUE TITLE
Exibir métricas para cada página

### ISSUE THREAD

**Issue by cv** [servicosgovbr/guia-de-servicos#68]
Preferencialmente, na própria página, de forma discreta (mais ou menos como no gov.uk), com um link para uma visualização geral das métricas do site todo.

**Comment by alklaser** [comment]
TODO: Escrever como hipótese.

**Comment by cv** [comment]
Depois do 169f6e5, teremos que repensar a coleta de métricas de acesso das páginas. Vou adicionar outros cartões para fazermos experimentos usando a API do Google Analytics e Piwik. Caso alguém lembre de um mecanismo de coleta de métricas que possa ser utilizado através de uma API interna ao produto, vamos falar sobre ele também! :)

**Comment by jeankirchner** [comment]
Podemos fechar esse agora que temos o Piwik?

**Comment by cv** [comment]
Fechando por enquanto, mas é provável que outro cartão apareça mais pra frente quando começarmos a falar da plataforma de desempenho.
