### ISSUE TITLE
Separar testes de integração dos testes unitários

### ISSUE THREAD

**Issue by erickpintor** [servicosgovbr/guia-de-servicos#71]
Por enquanto, temos apenas um teste de integração: `MainTest`.

Ele apenas sobe o contexto do Spring pra ver se nenhum erro ocorre neste momento.
Apesar de ser um teste simples, ele demora alguns segundos e isso prejudica bastante o tempo de feedback enquanto desenvolvendo a app.

Gradle suporta a separação dos tipos de tests em pastas diferentes. Aqui estão alguns materiais relevantes:

* http://selimober.com/blog/2014/01/24/separate-unit-and-integration-tests-using-gradle/
* https://github.com/brunodecarvalho/gradle-plugins/blob/master/integration-test.gradle

Lembrando que, ao importar o projeto no IntellJ, a pasta de integração deve ser reconhecida como uma pasta de teste.

**Comment by cv** [comment]
Pelos relatórios de cobertura, parece que as classes dentro de `br.gov.servicos.config` não estão sendo carregadas. Algumas possibilidades:

- ~~Os testes de integração não estão rodando no Snap~~
- Jacoco não está instrumentando os testes de integração
- Jacoco não está gerando relatório levando em conta a execução dos testes
- Contexto do Spring levantado pelo MainTest não chega a executar as configurações (mais provável)

**Comment by erickpintor** [comment]
Jacoco coverage foi adicionado como parte da task ```integrationTest```. Coverage agora está em 93%.
