### ISSUE TITLE
Plano de Iterações

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/guia-de-servicos#73]
Documenta como as equipes do projeto irão utilizar o Método Ágil (SCRUM) ao longo do projeto. Deverá indicar a ferramenta apropriada para uso do Método. Também faz parte do plano de projetos uma visão mais pormenorizada da metodologia a ser adotada e de seus fatores críticos de sucesso. No entanto, o método a ser adotado só será definido na primeira fase do projeto assim como todas as ferramentas que serão utilizadas.

**Comment by erickpintor** [comment]
Primeira versão submetida: https://github.com/servicosgovbr/guia-de-servicos/blob/master/docs/estrategia/plano_iteracoes/index.md

Commit: https://github.com/servicosgovbr/guia-de-servicos/commit/9359cd1384360e44d3121539b0314c425159d5df
