### ISSUE TITLE
Mapa de atores do sistema (contém Plano de Comunicações)

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/guia-de-servicos#74]
Este diagrama conterá todas as pessoas que precisam ser envolvidas no projeto, seu nível e descrição de responsabilidade, importância do engajamento para sucesso da metodologia, além dos papéis mais ativos ao longo do trabalho, como Gerente de Produto, eventuais substitutos e membros da equipe da empresa consultora.

O Plano de Comunicações
Documenta e identifica as partes interessadas, o que, como, quem, quando, porque e onde será comunicado cada tipo de informação e ainda como isto influencia no projeto.

**Comment by oliviagj** [comment]
Visual: https://thoughtworks.box.com/s/nfdbbu2f6jtbhowix7izzguvjgafatze
Planilha: https://thoughtworks.box.com/s/zje102tr50pd0a5crmkguulnxqdtuyrg

**Comment by sahrosa** [comment]
Ajustes realizados no .ods!
