### ISSUE TITLE
Estudo sobre portais de serviços de outros governos

### ISSUE THREAD

**Issue by oliviagj** [servicosgovbr/guia-de-servicos#78]
Estudo sobre portais de serviços de outros governos: realiza uma busca de portais de serviços de governos de outros países, considerando um mínimo de 10 portais e 20 variáveis de comparação entre os mesmos, que serão definidos em tempo de plano de projeto.

**Comment by sahrosa** [comment]
Finalizamos e colocamos no box! :) Falta adicionar nos docs do github #ossama

**Comment by caduvieira** [comment]
Pode ser útil também o vocabulário de serviços governamentais do EC que participamos um pouco para criação [1][2]. Também os use cases podem ser úteis para criar os cenários futuros. [3]

[1] https://joinup.ec.europa.eu/asset/core_public_service/description
[2] http://joinup.ec.europa.eu/site/core_vocabularies/Core_Vocabularies_v1.1/Core_Vocabularies_v1.1.htm
[3] http://xml.fido.gov/stratml/carmel/CPSVUCwStyle.xml#_d4534534-beb4-11e4-8393-21709fc53161

**Comment by augusto-herrmann** [comment]
Bem lembrado, Cadu. Eu tinha falado sobre o cpsv durante o workshop, mas você lembrou esses _use cases_ que podem ser úteis também.

Sugiro ver também o portal de serviços do governo de Mosocu [1], o qual pude conhecer recentemente.

[1] http://pgu.mos.ru/
