### ISSUE TITLE
Métricas sendo salvas de forma incorreta ao adicionar carga à aplicação

### ISSUE THREAD

**Issue by erickpintor** [servicosgovbr/guia-de-servicos#94]
Para fins de protótipo, utilizamos o próprio ElasticSearch para salvar as métricas de acesso aos serviços:

```java
@RequestMapping(value = "/servico/{id}", method = GET)
ModelAndView get(@PathVariable("id") String id) {
    Servico servico = servicos.save(buscaServico(id).withNovoAcesso());
    return new ModelAndView("servico", "servico", servico);
}
```

Porém, o ElasticSearch não garante a consistência entre busca e escrita com várias threads simultâneas.

O script a baixo (escrito em Clojure) dispara varias threads para efetuar 1000 chamadas para um serviço específico:

```clojure
(ns amiable-oasis
  (:require [clj-http.client :as http])) ;; depende da lib https://github.com/dakrone/clj-http

(defn perform-request 
  [& ignored-args]
  (Thread/sleep 500)
  (http/get "http://localhost:8080/servico/autorizacao-de-trabalho-a-estrangeiros"))
  
(dorun
  (pmap perform-request (range 1000)))
```

Após executá-lo várias vezes, e verificar a quantidade de acessos em cada uma delas, nota-se que o numero de acessos registrados é de 230 em média. Bem longe dos 1000 acessos esperados.

**Comment by cv** [comment]
Que tal disparar uma mensagem assíncrona (spring integration ou similar) e fazer a persistência dessas alterações em outra thread?



- cv

**Comment by erickpintor** [comment]
@cv A idéia é enfileirar estas alterações?

**Comment by cv** [comment]
Isso... Aí a thread escrevendo fica enfileirada enquanto as threads lendo ficam livres. Sem testar não dá pra saber se isso vai funcionar bem, especialmente se a gente partir pra uma  configuração em cluster. 



- cv

**Comment by erickpintor** [comment]
@cv Também fiquei preocupado com a configuração de cluster. Mas acho que só testando pra ver.

O script que coloquei na issue é bem simples, no entanto, ele tem tudo o que a gente precisa pra testar novamente. Mesmo em cluster.

Concordo com a fila de eventos.

**Comment by cv** [comment]
Mudamos a arquitetura de forma a manter o ElasticSearch read-only (com exceção da carga inicial e formulários de feedback).
